#file:e:\Desktop\ariadne\backend\environment.yml
name: ariadne-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - fastapi==0.104.1
    - uvicorn==0.24.0
    - sqlalchemy==1.4.49  # 降级到与databases兼容的版本
    - pymysql==1.1.0
    - python-jose==3.3.0
    - passlib==1.7.4
    - python-multipart==0.0.6
    - pydantic==2.5.0
    - pydantic-settings==2.0.3
    - alembic==1.13.0
    - bcrypt==4.0.1
    - databases==0.8.0